services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: registration_user
        uid: 1000
    image: registration-app
    container_name: registration-app-server
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - registration-network

  # Nxin Service
  nginx:
    image: nginx:alpine
    container_name: registration-app-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - registration-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: registration-app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "33061:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - registration-network

networks:
  registration-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
